COMPUTED VALUES:
aibrix:
  enabled: false
  modelName: served-model
  port: 8200
autoscaling:
  enabled: false
  maxReplicaCount: 16
  prometheusQuery: |
    max(router_central_queue_length{namespace="vllm"})
  threshold: "16"
backend: router
batchSize: 8
global:
  imageRegistry: reg.local:32000
images:
  cpuHash: vllm-cpu-hash:latest
  redis: redis:7-alpine
  router: kv-router:latest
  sidecar: kv-sidecar:latest
  vllm: quay.io/ascend/vllm-ascend:v0.11.0rc0
modelVolume:
  create: true
  nfsPath: /saeid/models/qwen3-8b
  nfsServer: nfs.local
pin:
  enabled: true
  nodeName: node1
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
replicas:
  router: 1
  vllm: 16
router:
  kvAware: true
  lenAware: true
  lenPolicy: short_first
  mode: pull
