{{- if .Values.modelVolume.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen-local-pvc
  namespace: vllm
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: qwen-local-pv
{{- end }}
