apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-qwen
  namespace: vllm
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: vllm-qwen
  podMetricsEndpoints:
    - path: /metrics
      port: http
      scheme: http
      honorLabels: true
      interval: 1s

    - path: /metrics
      port: vllmthr
      scheme: http
      honorLabels: true
      interval: 1s

---
{{- if eq (lower .Values.backend) "router" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kv-router
  namespace: vllm
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: router-service
  podMetricsEndpoints:
    - path: /metrics
      port: http
      scheme: http
      honorLabels: true
      interval: 1s

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kv-sidecar
  namespace: vllm
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: vllm-qwen
  podMetricsEndpoints:
    - path: /metrics
      port: sidecar-http
      scheme: http
      honorLabels: true
      interval: 1s
{{- end }}