#!/usr/bin/env python3
"""
vLLM Prefix Caching Stress Test

This script performs stress testing on vLLM with focus on:
- CPU-NPU KV cache offloading monitoring
- Request latency and throughput measurement

Prompts are loaded from JSON files generated by generate_prompts.py
"""

import asyncio
import aiohttp
import time
import json
import re
import subprocess
import threading
import csv
import argparse
from datetime import datetime
from collections import defaultdict
import statistics
from dataclasses import dataclass, asdict
from typing import List, Optional
from pathlib import Path


@dataclass
class TransferEvent:
    timestamp: datetime
    direction: str
    elapsed_seconds: float  # Time since test started


class KVTransferMonitor:
    def __init__(self, container_name, base_url="http://localhost:10000"):
        self.container_name = container_name
        self.base_url = base_url
        self.completions_url = f"{base_url}/v1/completions"
        
        self.transfer_events: List[TransferEvent] = []
        self.request_results = []
        self.all_transfers = []
        
        self.monitoring_active = False
        self.requests_in_flight = 0
        self.test_start_time = None  # Track when test starts


    def monitor_docker_logs(self):
        """Monitor Docker logs for transfers"""
        print(f"📡 Starting log monitor for container: {self.container_name}\n")
        
        try:
            process = subprocess.Popen(
                f"docker logs -f --tail 0 {self.container_name} 2>&1",
                shell=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                bufsize=1
            )
            direction_pattern = re.compile(r'direction=(h2d|d2h)')
            
            # Read continuously from the start
            while self.monitoring_active:
                line = process.stdout.readline()
                if not line:
                    break
                
                # Check for transfer direction
                match = direction_pattern.search(line)
                if match:
                    direction = match.group(1)
                    elapsed = time.time() - self.test_start_time if self.test_start_time else 0
                    
                    # Store in both formats for compatibility
                    self.all_transfers.append({
                        'direction': direction,
                        'timestamp': time.time(),
                        'line': line.strip()
                    })
                    
                    self.transfer_events.append(TransferEvent(
                        timestamp=datetime.now(),
                        direction=direction,
                        elapsed_seconds=elapsed
                    ))
                    
                    print(f"📡 Detected: {direction}")
            
            process.terminate()
            print("✅ Monitoring stopped")
        except Exception as e:
            print(f"❌ Error monitoring logs: {e}")


    async def send_request(self, session, request_id, prompt):
        """Send request"""
        payload = {
            "model": "qwen3-8b",
            "prompt": prompt,
            "max_tokens": 256,
            "temperature": 0.7,
        }
        
        self.requests_in_flight += 1
        start_time = time.time()
        elapsed_at_start = start_time - self.test_start_time if self.test_start_time else 0
        
        try:
            async with session.post(self.completions_url, json=payload) as response:
                result = await response.json()
                latency = time.time() - start_time
                elapsed_at_end = time.time() - self.test_start_time if self.test_start_time else 0
                
                self.requests_in_flight -= 1
                
                return {
                    'request_id': request_id,
                    'success': response.status == 200,
                    'latency': latency,
                    'tokens': result.get('usage', {}).get('completion_tokens', 0),
                    'prompt_tokens': result.get('usage', {}).get('prompt_tokens', 0),
                    'prompt_length': len(prompt),
                    'timestamp': datetime.now().isoformat(),
                    'elapsed_start': elapsed_at_start,
                    'elapsed_end': elapsed_at_end
                }
        except Exception as e:
            self.requests_in_flight -= 1
            return {
                'request_id': request_id,
                'success': False,
                'latency': time.time() - start_time,
                'error': str(e),
                'elapsed_start': elapsed_at_start,
                'elapsed_end': time.time() - self.test_start_time if self.test_start_time else 0
            }
    
    def load_prompts_from_json(self, json_file: str) -> tuple[List[str], dict]:
        """Load prompts from JSON file"""
        print(f"📂 Loading prompts from: {json_file}")
        
        with open(json_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        prompts = data.get('prompts', [])
        metadata = data.get('metadata', {})
        
        print(f"✅ Loaded {len(prompts)} prompts")
        print(f"   Strategy: {metadata.get('strategy', 'unknown')}")
        print(f"   Generated at: {metadata.get('generated_at', 'unknown')}")
        
        if 'analysis' in metadata:
            analysis = metadata['analysis']
            print(f"   Avg tokens: ~{analysis.get('estimated_avg_tokens', 0):.0f}")
            print(f"   Shared tokens: ~{analysis.get('estimated_shared_tokens', 0):.0f}")
            print(f"   Cache potential: {analysis.get('cache_potential', 'unknown')}")
        
        return prompts, metadata
    
    async def run_stress_test(self, prompts: List[str], metadata: dict, concurrency: int = 50):
        """Run stress test with provided prompts"""
        strategy = metadata.get('strategy', 'unknown')
        num_requests = len(prompts)
        
        print(f"\n{'='*80}")
        print("🚀 Starting Stress Test")
        print(f"{'='*80}")
        print(f"   Requests: {num_requests}")
        print(f"   Concurrency: {concurrency}")
        print(f"   Prompt strategy: {strategy}")
        print(f"   Target: {self.base_url}")
        print(f"   Container: {self.container_name}\n")
        
        # Record test start time
        self.test_start_time = time.time()
        
        # Start monitoring
        self.monitoring_active = True
        monitor_thread = threading.Thread(target=self.monitor_docker_logs, daemon=True)
        monitor_thread.start()
        
        await asyncio.sleep(1)
        
        # Analyze sample prompts before sending
        self.analyze_prompt_characteristics(prompts[:10])
        
        # Run requests
        timeout = aiohttp.ClientTimeout(total=300)
        connector = aiohttp.TCPConnector(limit=concurrency)
        
        print("\n📤 Sending requests...\n")
        start_time = time.time()
        
        async with aiohttp.ClientSession(timeout=timeout, connector=connector) as session:
            semaphore = asyncio.Semaphore(concurrency)
            
            async def bounded_request(req_id, prompt):
                async with semaphore:
                    return await self.send_request(session, req_id, prompt)
            
            tasks = [bounded_request(i, p) for i, p in enumerate(prompts)]
            
            completed = 0
            results = []
            for coro in asyncio.as_completed(tasks):
                result = await coro
                results.append(result)
                completed += 1
                if completed % 20 == 0:
                    print(f"✓ Completed {completed}/{num_requests} requests")
        
        total_time = time.time() - start_time
        
        print("\n⏹️  Stopping monitoring...\n")
        self.monitoring_active = False
        await asyncio.sleep(2)
        
        self.analyze_results(results, total_time, strategy)
    
    def analyze_prompt_characteristics(self, sample_prompts):
        """Analyze prompt characteristics for caching potential"""
        print("\n" + "="*80)
        print("🔍 PROMPT ANALYSIS (First 10 prompts)")
        print("="*80)
        
        for i, prompt in enumerate(sample_prompts):
            char_count = len(prompt)
            # Rough token estimate (1 token ≈ 4 characters for English)
            estimated_tokens = char_count // 4
            
            print(f"\nPrompt {i}:")
            print(f"  Characters: {char_count}")
            print(f"  Estimated tokens: ~{estimated_tokens}")
            print(f"  Preview: {prompt[:100]}...")
        
        # Check for shared prefixes
        if len(sample_prompts) >= 2:
            print(f"\n📊 Prefix Sharing Analysis:")
            
            # Find common prefix between first two prompts
            prompt1 = sample_prompts[0]
            prompt2 = sample_prompts[1]
            
            common_chars = 0
            for c1, c2 in zip(prompt1, prompt2):
                if c1 == c2:
                    common_chars += 1
                else:
                    break
            
            shared_tokens = common_chars // 4
            
            print(f"  Common prefix characters: {common_chars}")
            print(f"  Estimated shared tokens: ~{shared_tokens}")
            
            if shared_tokens > 128:
                print(f"  ✅ EXCELLENT - Shared prefix exceeds block_size=128")
            elif shared_tokens > 64:
                print(f"  ✓ GOOD - Shared prefix exceeds 64 tokens")
            elif shared_tokens > 16:
                print(f"  ⚠️  MODERATE - Shared prefix is 16-64 tokens")
            else:
                print(f"  ❌ LOW - Shared prefix < 16 tokens, cache may not help")
        
        print("="*80 + "\n")
    
    def analyze_results(self, results, total_time, strategy):
        """Analyze results"""
        print("="*80)
        print("📊 STRESS TEST RESULTS")
        print("="*80)
        
        successful = [r for r in results if r['success']]
        latencies = [r['latency'] for r in successful]
        total_tokens = sum(r.get('tokens', 0) for r in successful)
        
        print(f"\n📈 Request Statistics:")
        print(f"   Strategy: {strategy}")
        print(f"   Total: {len(results)}")
        print(f"   Successful: {len(successful)} ({100*len(successful)/len(results):.1f}%)")
        print(f"   Duration: {total_time:.2f}s")
        print(f"   Throughput: {len(results)/total_time:.2f} req/s")
        
        if latencies:
            print(f"\n⏱️  Latency:")
            print(f"   Mean: {statistics.mean(latencies):.3f}s")
            print(f"   Median: {statistics.median(latencies):.3f}s")
            print(f"   P95: {sorted(latencies)[int(0.95*len(latencies))]:.3f}s")
            print(f"   Min: {min(latencies):.3f}s")
            print(f"   Max: {max(latencies):.3f}s")
        
        print(f"\n🔤 Tokens: {total_tokens} ({total_tokens/total_time:.0f} tok/s)")
        
        # Count transfers by direction
        if self.all_transfers:
            h2d_count = sum(1 for t in self.all_transfers if t['direction'] == 'h2d')
            d2h_count = sum(1 for t in self.all_transfers if t['direction'] == 'd2h')
            
            print(f"\n🔄 KV Cache Transfers:")
            print(f"   h2d (CPU→NPU): {h2d_count}")
            print(f"   d2h (NPU→CPU): {d2h_count}")
            print(f"   Total: {len(self.all_transfers)}")
        else:
            print(f"\n⚠️  No transfer events detected")
        
        # Save results
        self.save_results(results, total_time, strategy)
        self.save_transfers_csv(strategy)
        
        print("\n" + "="*80)
    
    def save_results(self, results, total_time, strategy):
        """Save results to JSON"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Create results directory if it doesn't exist
        results_dir = Path("results")
        results_dir.mkdir(exist_ok=True)
        
        data = {
            'strategy': strategy,
            'summary': {
                'total_requests': len(results),
                'successful': len([r for r in results if r['success']]),
                'total_time': total_time,
                'total_tokens': sum(r.get('tokens', 0) for r in results if r['success']),
                'total_transfers': len(self.all_transfers),
                'h2d_transfers': sum(1 for t in self.all_transfers if t['direction'] == 'h2d'),
                'd2h_transfers': sum(1 for t in self.all_transfers if t['direction'] == 'd2h'),
            },
        }
        
        filename = results_dir / f'results_{strategy}_{timestamp}.json'
        with open(filename, 'w') as f:
            json.dump(data, f, indent=2)
        
        print(f"\n💾 Results saved: {filename}")

    def save_transfers_csv(self, strategy):
        """Save transfer events to CSV"""
        if not self.all_transfers:
            print("⚠️  No transfer events to save")
            return
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        results_dir = Path("results")
        results_dir.mkdir(exist_ok=True)
        
        filename = results_dir / f'transfers_{strategy}_{timestamp}.csv'
        
        with open(filename, 'w', newline='') as f:
            writer = csv.writer(f)
            
            # Write header
            writer.writerow(['timestamp', 'direction', 'elapsed_seconds', 'log_line'])
            
            # Write transfer events
            for transfer in self.all_transfers:
                # Calculate elapsed time from test start
                elapsed = transfer['timestamp'] - self.test_start_time if self.test_start_time else 0
                
                writer.writerow([
                    datetime.fromtimestamp(transfer['timestamp']).isoformat(),
                    transfer['direction'],
                    f"{elapsed:.3f}",
                    transfer['line']
                ])
        
        print(f"💾 Transfers saved: {filename}")
        print(f"   Total events: {len(self.all_transfers)}")
        print(f"   h2d: {sum(1 for t in self.all_transfers if t['direction'] == 'h2d')}")
        print(f"   d2h: {sum(1 for t in self.all_transfers if t['direction'] == 'd2h')}")


async def main():
    parser = argparse.ArgumentParser(
        description='Run vLLM prefix caching stress test',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run test with prompts from prompts/ folder
  python stress_test.py -f prompts/prompts_long_prefix_20250128_120000.json

  # Specify custom concurrency
  python stress_test.py -f prompts/prompts_long_prefix.json -c 100

  # Specify container name and API URL
  python stress_test.py -f prompts/prompts.json --container my-vllm --url http://localhost:8000
        """
    )
    
    parser.add_argument(
        '-f', '--file',
        required=True,
        type=str,
        help='JSON file containing prompts (generated by generate_prompts.py)'
    )
    
    parser.add_argument(
        '-c', '--concurrency',
        type=int,
        default=50,
        help='Maximum concurrent requests (default: 50)'
    )
    
    parser.add_argument(
        '--container',
        type=str,
        help='Docker container name (auto-detect if not specified)'
    )
    
    parser.add_argument(
        '--url',
        type=str,
        default='http://localhost:10000',
        help='vLLM API base URL (default: http://localhost:10000)'
    )
    
    args = parser.parse_args()
    
    # Check if prompt file exists
    if not Path(args.file).exists():
        print(f"❌ Prompt file not found: {args.file}")
        print("   Generate prompts first using: python generate_prompts.py")
        return
    
    # Find container if not specified
    container_name = args.container
    if not container_name:
        try:
            result = subprocess.run(
                ['docker', 'ps', '--format', '{{.Names}}\t{{.Image}}'],
                capture_output=True,
                text=True,
                check=True
            )
            
            for line in result.stdout.split('\n'):
                if 'vllm-ascend' in line.lower():
                    container_name = line.split('\t')[0]
                    break
            
            if not container_name:
                print("❌ No vLLM container found! Please specify --container")
                return
            
            print(f"✅ Found container: {container_name}\n")
            
        except Exception as e:
            print(f"❌ Error detecting container: {e}")
            print("   Please specify container name with --container")
            return
    
    # Create monitor
    monitor = KVTransferMonitor(
        container_name=container_name,
        base_url=args.url
    )
    
    # Load prompts
    prompts, metadata = monitor.load_prompts_from_json(args.file)
    
    if not prompts:
        print("❌ No prompts found in file!")
        return
    
    # Run stress test
    await monitor.run_stress_test(
        prompts=prompts,
        metadata=metadata,
        concurrency=args.concurrency
    )


if __name__ == "__main__":
    asyncio.run(main())