# Use a slim Python image as a base
FROM python:3.10-slim
ENV http_proxy=http://peulerosweb:EulerOS_123@172.18.100.92:8080
ENV https_proxy=http://peulerosweb:EulerOS_123@172.18.100.92:8080
RUN apt update


# Set the working directory
WORKDIR /app

COPY ./requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir \
--trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

CMD ["bash"]
# Copy the subscriber script into the container
# COPY ./src/zmq_subscriber.py .

# Command to run the script when the container starts
# CMD ["python", "zmq_subscriber.py"]
