FROM ubuntu:24.04
RUN apt update && apt install -y wget ca-certificates

# Fetch huawei ssl certificates
RUN wget --no-check-certificate https://gitlab-uk.rnd.huawei.com/sir_lab/docs/-/raw/master/Infrastructure/config/certs/HuaweiITRootCA.pem -O /usr/local/share/ca-certificates/HuaweiITRootCA.crt
RUN wget --no-check-certificate https://gitlab-uk.rnd.huawei.com/sir_lab/docs/-/raw/master/Infrastructure/config/certs/HuaweiItEnterpriseCA1.pem -O /usr/local/share/ca-certificates/HuaweiItEnterpriseCA1.crt
RUN wget --no-check-certificate https://gitlab-uk.rnd.huawei.com/sir_lab/docs/-/raw/master/Infrastructure/config/certs/huawei.pem -O /usr/local/share/ca-certificates/huawei.crt
RUN wget --no-check-certificate https://gitlab-uk.rnd.huawei.com/sir_lab/docs/-/raw/master/Infrastructure/config/certs/HuaweiSecureInternetProxyCA.pem -O /usr/local/share/ca-certificates/HuaweiSecureInternetProxyCA.crt
RUN wget --no-check-certificate https://gitlab-uk.rnd.huawei.com/sir_lab/docs/-/raw/master/Infrastructure/config/certs/HuaweiWebSecureInternetGatewayCA.pem -O /usr/local/share/ca-certificates/HuaweiWebSecureInternetGatewayCA.crt

# Install SSL certificates
RUN update-ca-certificates
RUN apt-get update && apt-get install -y file bash
RUN file /bin/bash
CMD ["bash"]

