# Use a slim Python image as a base
FROM python:3.10-slim

RUN apt update && apt install -y wget ca-certificates

# Fetch huawei ssl certificates
RUN wget --no-check-certificate https://gitlab-uk.rnd.huawei.com/sir_lab/docs/-/raw/master/Infrastructure/config/certs/HuaweiITRootCA.pem -O /usr/local/share/ca-certificates/HuaweiITRootCA.crt
RUN wget --no-check-certificate https://gitlab-uk.rnd.huawei.com/sir_lab/docs/-/raw/master/Infrastructure/config/certs/HuaweiItEnterpriseCA1.pem -O /usr/local/share/ca-certificates/HuaweiItEnterpriseCA1.crt
RUN wget --no-check-certificate https://gitlab-uk.rnd.huawei.com/sir_lab/docs/-/raw/master/Infrastructure/config/certs/huawei.pem -O /usr/local/share/ca-certificates/huawei.crt
RUN wget --no-check-certificate https://gitlab-uk.rnd.huawei.com/sir_lab/docs/-/raw/master/Infrastructure/config/certs/HuaweiSecureInternetProxyCA.pem -O /usr/local/share/ca-certificates/HuaweiSecureInternetProxyCA.crt
RUN wget --no-check-certificate https://gitlab-uk.rnd.huawei.com/sir_lab/docs/-/raw/master/Infrastructure/config/certs/HuaweiWebSecureInternetGatewayCA.pem -O /usr/local/share/ca-certificates/HuaweiWebSecureInternetGatewayCA.crt

# Install SSL certificates
RUN update-ca-certificates

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["bash"]
# Copy the subscriber script into the container
# COPY ./src/zmq_subscriber.py .

# Command to run the script when the container starts
# CMD ["python", "zmq_subscriber.py"]