{{- if .Values.modelVolume.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-nfs-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: models-nfs-pv
{{- end }}