{{- if .Values.mooncake.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mooncake-config
  namespace: {{ .Release.Namespace }}
data:
  mooncake.json: |
    {
      "metadata_server": "P2PHANDSHAKE",
      "protocol": "ascend",
      "device_name": "",
      "master_server_address": {{ .Values.mooncake.masterServerAddress | quote }},
      "global_segment_size": {{ .Values.mooncake.globalSegmentSize }},
      "preferred_segment": {{ .Values.mooncake.preferredSegment | default false }}
    }
{{- end }}
